default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        stages:
          - pre-commit
      - id: end-of-file-fixer
      - id: check-toml
        stages:
          - pre-commit
      - id: check-yaml
        stages:
          - pre-commit
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.7.3"
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        stages:
          - pre-commit
      - id: ruff-format
        stages:
          - pre-commit
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.10"
    hooks:
      - id: bandit
        language_version: python3
        exclude: (_test\.py|conftest\.py)$
        args:
          - -s
          - B404,B603,B310
        stages:
          - pre-commit
  -   repo: https://github.com/Yelp/detect-secrets
      rev: v1.5.0
      hooks:
      -   id: detect-secrets
          args: ['--exclude-files', '.*\.ipynb$', ]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
      - id: poetry-check
        stages:
          - pre-commit
      - id: poetry-lock
        args: ["--no-update", "--no-cache"]
        stages:
          - pre-commit
  - repo: https://github.com/tweag/FawltyDeps
    rev: v0.17.0
    hooks:
      - id: check-undeclared
        stages:
          - pre-commit
      - id: check-unused
        stages:
          - pre-commit
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.30.1
    hooks:
    - id: commitizen
    - id: commitizen-branch
      stages:
      - pre-push
