name: Bump Version
on:
  pull_request_target:
    types:
      - closed

jobs:
  bump-version:
    name: Bump Version
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == github.event.repository.default_branch
    runs-on: ubuntu-20.04
    env:
      PR_BRANCH_REF: ${{ github.event.pull_request.head.ref }}
      PR_BRANCH_SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Bump version
        run: |
          poetry version $(echo ${PR_BRANCH_REF} | cut -d "/" -f 1)
          echo "new_version=$(poetry version -s)" >> $GITHUB_ENV
      - name: Update repository
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add pyproject.toml
          git commit -m "Update version to ${{ env.new_version }}"
          git tag v${{ env.new_version }}
          git push --atomic origin ${{ github.event.repository.default_branch }} v${{ env.new_version }}
      - name: Build and Publish package
        run: |
          poetry build
          poetry publish -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
