name: tag and release new version

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: create new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: v5.1.0
      - name: Install poetry
        run: pipx install poetry
      - name: Build package
        run: poetry build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
